name: deploy pags to cloudflare

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "pages/**/*"

env:
  IS_CI: 1

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: bash ./scripts/build.sh

      - name: Publish page/landing
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.LANDING_PROJECT_NAME }}
          directory: pages/landing/dist

      - name: Publish page/docs
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.DOCS_PROJECT_NAME }}
          directory: pages/docs/dist
